# =============================================================================
# A.I.M.S. — Google Cloud Build Pipeline
# =============================================================================
# Triggers: Push to main branch (configured in GCP Console or via gcloud)
#
# What it does:
#   1. Install + lint + test backend
#   2. Install + lint + build frontend
#   3. Build Docker images
#   4. Push to Artifact Registry
#   5. Deploy to Cloud Run (or SSH to VPS)
#
# Setup:
#   gcloud builds submit --config=cloudbuild.yaml
#   — OR —
#   Connect GitHub repo in Cloud Build Triggers UI
# =============================================================================

steps:
  # ── Step 1: Backend — Install, Lint, Build, Test ──
  - id: backend-install
    name: node:20-alpine
    dir: backend/uef-gateway
    entrypoint: npm
    args: ['ci']

  - id: backend-lint
    name: node:20-alpine
    dir: backend/uef-gateway
    entrypoint: npm
    args: ['run', 'lint']
    waitFor: ['backend-install']

  - id: backend-build
    name: node:20-alpine
    dir: backend/uef-gateway
    entrypoint: npm
    args: ['run', 'build']
    waitFor: ['backend-install']

  - id: backend-test
    name: node:20-alpine
    dir: backend/uef-gateway
    entrypoint: npm
    args: ['test']
    waitFor: ['backend-build']

  # ── Step 2: Frontend — Install, Lint, Build ──
  - id: frontend-install
    name: node:20-alpine
    dir: frontend
    entrypoint: npm
    args: ['ci']

  - id: frontend-lint
    name: node:20-alpine
    dir: frontend
    entrypoint: npm
    args: ['run', 'lint']
    waitFor: ['frontend-install']

  - id: frontend-build
    name: node:20-alpine
    dir: frontend
    entrypoint: npm
    args: ['run', 'build']
    waitFor: ['frontend-install']

  # ── Step 3: Build Docker Images ──
  - id: docker-gateway
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway:${SHORT_SHA}'
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway:latest'
      - -f
      - backend/uef-gateway/Dockerfile
      - backend/uef-gateway
    waitFor: ['backend-test']

  - id: docker-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${SHORT_SHA}'
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:latest'
      - -f
      - frontend/Dockerfile
      - frontend
    waitFor: ['frontend-build']

  # ── Step 4: Push to Artifact Registry ──
  - id: push-gateway
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway'
    waitFor: ['docker-gateway']

  - id: push-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend'
    waitFor: ['docker-frontend']

  # ── Step 5: Deploy to Cloud Run ──
  - id: deploy-gateway
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - aims-gateway
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --port=3001
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
      - --allow-unauthenticated
      - --set-env-vars=NODE_ENV=production,PORT=3001
    waitFor: ['push-gateway']

  - id: deploy-frontend
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - aims-frontend
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --port=3000
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=5
      - --allow-unauthenticated
    waitFor: ['push-frontend']

# ── Substitution Variables ──
# Override these in your Cloud Build trigger config or via --substitutions
substitutions:
  _REGION: us-central1
  _REPO: aims-docker

# ── Images to push (Cloud Build auto-pushes these) ──
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:latest'

# ── Build options ──
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
timeout: 1200s
