# =============================================================================
# A.I.M.S. — Google Cloud Build Pipeline (CI: Build & Push)
# =============================================================================
# Triggers: Push to main branch (via GitHub Actions → gcloud builds submit)
#
# VPS-first architecture:
#   All services run on VPS (76.13.96.107) via docker-compose.prod.yml
#   This pipeline only builds images and pushes to Artifact Registry.
#   VPS pulls latest images via deploy.sh.
#
# What it does:
#   1. Build Docker images (gateway, frontend, agents)
#   2. Push to Artifact Registry (us-central1-docker.pkg.dev)
#   — No Cloud Run deploys. VPS is the deployment target. —
#
# GPU inference (PersonaPlex/Nemotron) handled separately via Vertex AI.
#
# Setup:
#   gcloud builds submit --config=cloudbuild.yaml
#   — OR —
#   Connect GitHub repo in Cloud Build Triggers UI
# =============================================================================

steps:
  # ── Step 1: Build Docker Images ──
  # (npm install + build happen inside each Dockerfile — no pre-build steps needed)
  - id: docker-gateway
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway:${_SHORT_SHA}'
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway:latest'
      - -f
      - backend/uef-gateway/Dockerfile
      - backend/uef-gateway

  - id: docker-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${_SHORT_SHA}'
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:latest'
      - -f
      - frontend/Dockerfile
      - .

  # ── Step 2: Push to Artifact Registry ──
  - id: push-gateway
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway'
    waitFor: ['docker-gateway']

  - id: push-frontend
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend'
    waitFor: ['docker-frontend']

  # ── Step 3: Build Agent Images ──
  - id: docker-research-ang
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/research-ang:${_SHORT_SHA}'
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/research-ang:latest'
      - -f
      - backend/agents/research-ang/Dockerfile
      - backend/agents/research-ang

  - id: docker-router-ang
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/router-ang:${_SHORT_SHA}'
      - -t
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/router-ang:latest'
      - -f
      - backend/agents/router-ang/Dockerfile
      - backend/agents/router-ang

  - id: push-research-ang
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/research-ang'
    waitFor: ['docker-research-ang']

  - id: push-router-ang
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/router-ang'
    waitFor: ['docker-router-ang']

# ── Substitution Variables ──
# Override these in your Cloud Build trigger config or via --substitutions
substitutions:
  _REGION: us-central1
  _REPO: aims-docker
  _SHORT_SHA: local

# ── Images to push (Cloud Build auto-pushes these) ──
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway:${_SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/uef-gateway:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:${_SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/frontend:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/research-ang:${_SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/research-ang:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/router-ang:${_SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/router-ang:latest'

# ── Build options ──
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
timeout: 1200s
