version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aims
    ports:
      - "5432:5432"
    volumes:
      - aims-db-data:/var/lib/postgresql/data

volumes:
  aims-db-data:
